### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise-utils#11]
```scss
.hide--print {
    display: none;
    visibility: hidden;
  }

.show--print {
    display: block;
    visibility: visible;
  }
```
