### ISSUE TITLE
Add: Type

### ISSUE THREAD

**Issue by ghost** [ConciseCSS/concise-utils#11]
``` scss

.h1, .h2, .h3 {
  a {
    color: getColor(text, primary);

    &:hover,
    &:focus {
      color: getColor(base, primary);
      text-decoration: none;
    }
  }
}

.pre--flat {
  background-color: transparent;
  border: 0;
  border-radius: 0;
  padding: 0;
}

```
