### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise-utils#13]
```scss
.italic { font-style: italic; }

.bold { font-weight: bold; }

.small {
  font-size: 75%;
  vertical-align: text-bottom;
}

.small {
  font-size: $font-small-size;
  vertical-align: text-bottom;
}

.pre--flat {
  background-color: transparent;
  border: 0;
  border-radius: 0;
  padding: 0;
}
```
