### ISSUE TITLE
Add: Blockquote

### ISSUE THREAD

**Issue by ghost** [ConciseCSS/concise-utils#2]
``` scss
//
// Modifiers
// ---------

.blockquote--reverse {
  border-left: none;
  border-right: 1px solid getColor(base, lines);
  text-align: right;
}
```
