### ISSUE TITLE
Add list with nested numbers

### ISSUE THREAD

**Issue by ghost** [ConciseCSS/concise-utils#24]
``` scss
ol { counter-reset: item; }
li:before { 
  content: counters(item, ".") " "; 
  counter-increment: item;
}
```
