### ISSUE TITLE
Form stuff

### ISSUE THREAD

**Issue by ghost** [ConciseCSS/concise-utils#33]
```scss
// If not inline, then add a line break                                                                                        
:not(._inline) > label:after {                                                                                                 
  content: "\A";                                                                                                               
  white-space: pre;                                                                                                            
}                                                                                                                              
                                                                                                                               
div._inline > label {                                                                                                          
  margin-right:1.5em;                                                                                                          
}
```

Thanks to @FredHall
