### ISSUE TITLE
Blockquote reverse 

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise-utils#6]
```scss
.blockquote--reverse {
  border-left: none;
  border-right: 1px solid getColor(base, lines);
  text-align: right;
}
```
