### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise-utils#8]
```scss
//
// Descendents
// -----------

// Help text
.input--help {
  color: getColor(text, secondary);
  display: block;
  font-size: pxToEm(12);
  font-weight: bold;
  margin-top: unitSize(1);
}


//
// Form Modifiers
// --------------

// Inline Form
.form--inline {
  input,
  select,
  textarea { margin-bottom: unitSize(3, -4); }

  @media (min-width: $bp-extra-small) {
    input,
    select,
    textarea {
      display: inline-block;
      margin-bottom: 0;
      vertical-align: middle;
      width: auto;
    }

    label {
      display: inline;
      margin-right: .5em;
      vertical-align: middle;
    }

    input + label { margin-left: 1em; }
  }
}

@if $non-responsive == true {
  .nonresponsive {
    .form--inline {
      input,
      select,
      textarea {
        display: inline-block;
        margin-bottom: 0;
        vertical-align: middle;
        width: auto;
      }

      label {
        display: inline;
        margin-right: .5em;
        vertical-align: middle;
      }

      input + label { margin-left: 1em; }
    }
  }
}


//
// Input Modifiers
// ---------------

// Small
.input--small {
  font-size: pxToEm(12);
  height: unitSize(3);
}

// Large
.input--large {
  height: unitSize(6);
  font-size: pxToEm(16);
}

// Flat
.input--flat {
  background-color: transparent;
  border-color: transparent;
  box-shadow: none;

  &:focus { border-color: getColor(blue, lighter); }
}

// Success
.input--success {
  background-color: rgba(getColor(state, success), .15);
  border-color: getColor(state, success);

  &:focus { border-color: getColor(state, success); }
}

// Warning
.input--warning {
  background-color: rgba(getColor(state, warning), .15);
  border-color: getColor(state, warning);

  &:focus { border-color: getColor(state, warning); }
}

// Warning
.input--error {
  background-color: rgba(getColor(state, error), .15);
  border-color: getColor(state, error);

  &:focus { border-color: getColor(state, error); }
}

```
