### ISSUE TITLE
Add: Lists

### ISSUE THREAD

**Issue by ghost** [ConciseCSS/concise-utils#8]
``` scss
//
// Modifiers
// ---------

// Unstyled
.list--unstyled {
  list-style: none;
  padding-left: 0;

  li { padding-left: 0; }
}

// Inline
.list--inline li {
  display: inline;
  list-style: none;
  padding-left: 1.5em;

  &:first-child { padding-left: 0; }
}
```
