### ISSUE TITLE
Add: Print

### ISSUE THREAD

**Issue by ghost** [ConciseCSS/concise-utils#9]
``` scss
@media print {
  .show--print {
    display: block;
    visibility: visible;
  }

  .hide--print {
    display: none;
    visibility: hidden;
  }

  .h2, .h3 {
    orphans: 3;
    widows: 3;
  }

  .h2, .h3 { page-break-after: avoid; }


}
```
