### ISSUE TITLE
Extra heading sizes

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise-utils#9]
```scss
//
// Sizes
// -----

// Giga
.giga {
  font-size: pxToEm($giga-size * .75);

  @media (min-width: $bp-small) {
    font-size: pxToEm($giga-size);
  }
}

// Mega
.mega {
  font-size: pxToEm($mega-size * .75);

  @media (min-width: $bp-small) {
    font-size: pxToEm($mega-size);
  }
}

// Kilo
.kilo {
  font-size: pxToEm($kilo-size * .75);

  @media (min-width: $bp-small) {
    font-size: pxToEm($kilo-size);
  }
}
```
